"""Add PointLog model

Revision ID: 2595b9a28937
Revises: 998cfdb0d11c
Create Date: 2026-05-29 20:47:57.781788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2595b9a28937'
down_revision: Union[str, Sequence[str], None] = '998cfdb0d11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_logs_created_at'), 'point_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_logs_id'), 'point_logs', ['id'], unique=False)
    op.create_index(op.f('ix_point_logs_user_id'), 'point_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_logs_user_id'), table_name='point_logs')
    op.drop_index(op.f('ix_point_logs_id'), table_name='point_logs')
    op.drop_index(op.f('ix_point_logs_created_at'), table_name='point_logs')
    op.drop_table('point_logs')
    # ### end Alembic commands ###
