"""Add index to total_points

Revision ID: 3ba19333fd68
Revises: 2595b9a28937
Create Date: 2026-05-29 20:55:11.802729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba19333fd68'
down_revision: Union[str, Sequence[str], None] = '2595b9a28937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_total_points'), 'users', ['total_points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_total_points'), table_name='users')
    # ### end Alembic commands ###
